name: anomaly
description: Get anomalous calls 

data_url: s3://bucket/path/to/dataframe.csv 

export:
  slack:
    webhook_url: ""
  email:
    ids:
      - user@example.com
      - user2@example.com

filters:
  prediction_low_confidence:
    limit: 10
    annotation_key: "prediction_low_confidence"
    kwargs:
      confidence_threshold: 0.50
  low_asr_confidence:
    limit: 10
    annotation_key: "low_asr_confidence"
    kwargs:
      confidence_threshold: 0.50
  no_alternatives:
    limit: 10
    annotation_key: "no_alternatives"
  call_end_state:
    limit: 10
    annotation_key: "call_end_state"
    kwargs:
      end_state: ["REPROMPT_INTENT"]
